export const GET_PRICE = 'GET_PRICE'
export const GET_HISTORICAL = 'GET_HISTORICAL'
export const LOADING_HISTORICAL = 'LOADING_HISTORICAL'
export const SET_THRESHOLD = 'SET_THRESHOLD'

export const CHANGE_VIEW = 'CHANGE_VIEW'

export const GET_UPDATE_FREQ = 'GET_UPDATE_FREQ'
export const SET_UPDATE_FREQ = 'SET_UPDATE_FREQ'
